version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - ./app:/app
    command: python app.py

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
